### ISSUE TITLE
How to set poster URL after upload?

### ISSUE THREAD

**Issue by kylefox** [pqina/filepond-plugin-file-poster#1]
Plugin works fantastic 👍 but I'm stuck on something that I suspect is very simple...

I have a custom `server.process` that handles uploading videos. When the video has finished uploading, the server response includes a URL to the video's thumbnail image.

How can I change FilePond's poster after the video finishes uploading?

**Comment by rikschennink** [comment]
Thanks, glad to hear that!

A file poster can currently not be updated if the file is already in the list (the poster is created on load).

I've just published version `1.8.8` of FilePond which adds the option to set `metadata` when using the `addFile` method. Maybe it's an option to remove the processed file from the list and then re-add it (can pass an index to add it back in the right location)?

```js
pond.addFile(file, {
    index: 2,
    metadata: {
        poster: 'video-frame-01.jpg'
    }
});
```

**Comment by kylefox** [comment]
Hmm, that doesn't seem to work:

![image](https://user-images.githubusercontent.com/37838/42701253-4cf940ee-8683-11e8-8d25-27071a42aa27.png)

It looks like it's trying to call `load()` again on the file? I tried setting `server.load = null` (shown here) but it's the same result.

What I would _love_ is a way to set the file metadata in my custom `process` function, for example:

```javascript
process: (fieldName, file, metadata, load, error, progress, abort) => {
  
  performUpload(file, (response) => {
    // Upload completed and the server responded with something like:
    // { file_id: '12345', file_poster_url: 'https://placekitten.com/200/287' }
    load(response.file_id, { metadata: response.file_poster_url })
  })

}
```

Is there a way to accomplish something similar to this?

**Comment by rikschennink** [comment]
Hmm, it's a bit odd that it would send the file to the `load` end-point as there's no `type` supplied.

I'm not immediately sold on returning metadata from the process method, will think about this some more.

**Comment by rikschennink** [comment]
@kylefox Maybe it's not the load end point? Could it be the `url` variable you pass to poster is not a URL but something else?

**Comment by kylefox** [comment]
> Could it be the url variable you pass to poster is not a URL but something else?

Good thinking, however I tried with a hard-coded image URL and the result was the same. 🤔 

> I'm not immediately sold on returning metadata from the process method, will think about this some more.

Yeah, I'm not sure what the best API would be for modifying the poster for a particular file.

Just throwing out ideas ... what about a new `updateFile()` [instance method](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#methods)? For example:

```javascript
pond.element.addEventListener('FilePond:processfile', event => {
  pond.updateFile(event.detail.file, { metadata: { poster: 'video-frame-01.jpg' } })
})
```

(Note that this is only an issue immediately after uploading the file — if the user refreshes the page, I can set the poster properly by passing the `files:` parameter to `FilePond.create`)

**Comment by rikschennink** [comment]
This is something I've been working on to make editing images possible (which requires an update of the image preview plugin). 

The current angle is to have the `setMetadata` method throw an event after each change, plugins can then listen for this event and update the view accordingly.

The challenge is to group multiple `setMetadata` calls (for instance a new size and a new crop rectangle resulting in one view update instead of multiple)

**Comment by rikschennink** [comment]
Will see if I can test the poster situation again today.

**Comment by rikschennink** [comment]
I can't seem to reproduce the error, have you updated FilePond to version `1.8.8`

**Comment by kylefox** [comment]
> The challenge is to group multiple setMetadata calls (for instance a new size and a new crop rectangle resulting in one view update instead of multiple)

Hmm, yeah, that sounds like an interesting challenge 🤓

> I can't seem to reproduce the error, have you updated FilePond to version 1.8.8

Yeah, I'm using 1.8.8. I'm probably just hooking into `addFile` at the wrong time or something. 

It's not a problem for me that the poster isn't immediately available upload, so I'm totally cool just waiting until there's a "proper" way to update the poster with metadata someday. 👍

**Comment by achyutgauli** [comment]
My project preview image working fine but could not able to see image until I  clicking input field. I just want to see directly image uploaded in storage section of laravel without clicking on input field for the next time untill I changed the previous one pic.
![screenshot 58](https://user-images.githubusercontent.com/21071463/48603914-1fa8de80-e9a0-11e8-8c9c-a3dc3663038a.png)
![screenshot 59](https://user-images.githubusercontent.com/21071463/48603915-20417500-e9a0-11e8-8d86-66989fc8dbe1.png)

**Comment by rikschennink** [comment]
Changing the `poster` metadata property will now update the image.

```js
fileItem.setMetadata('poster', 'new-poster.jpeg');
```
