### ISSUE TITLE
input value filling with [object object]

### ISSUE THREAD

**Issue by hypy13** [pqina/filepond-plugin-file-poster#17]
when i use this plugin
the input value filling with [object Object]

why it changes the input value?
this is how i show the image
`files: [
                    {
                        options: {
                            type: 'local',
                            file: {
                                name: '{{ $value }}',
                                size: 3434,
                                type: 'image/png'
                            },
                            metadata: {
                                poster: '{{ assets($value) }}'
                            }
                        }
                    }
                ]`

**Comment by rikschennink** [comment]
I can't reproduce this problem here: https://pqina.github.io/filepond-plugin-file-poster/

**Comment by hypy13** [comment]
yea i forgot to put 
source

thanks
