### ISSUE TITLE
Allow color to be changed for Shadow, Error, and Success canvas elements

### ISSUE THREAD

**Issue by jakejackson1** [pqina/filepond-plugin-file-poster#21]
https://github.com/pqina/filepond-plugin-file-poster/blob/master/src/js/view/createPosterWrapperView.js#L43-L45

The colour used in the canvases for the Poster plugin is hardcoded and cannot be modified using CSS. It would be great to be able to change the color used for each canvas (possibly via CSS variables).

**Comment by rikschennink** [comment]
Add three new properties to control the color. CSS variables are currently not possible but this at least allows changing the colors used.

See updated plugin docs: https://pqina.nl/filepond/docs/api/plugins/file-poster/#properties
