### ISSUE TITLE
FilePoster along with FilePreview mutiple image get requests.

### ISSUE THREAD

**Issue by kodeine** [pqina/filepond-plugin-file-poster#3]
So i am using FilePoster along with FilePreview and i see 3 requests to the same image. I wonder why its happening.

**Comment by rikschennink** [comment]
You should use the FilePoster OR the ImagePreview plugin, not both. Both will request the image to calculate the image size and to render a preview, ImagePreview will request it a third time to generate a smaller version of the image.

**Comment by rowrowrowrow** [comment]
Hi,

I'd like to use both FilePoster and ImagePreview at the same time to view local images and newly added images. Using both, posters are loaded properly but the preview size is incorrect and previews for new images are correct. Is there anyway to resolve this? Happy to help.
