### ISSUE TITLE
poster and preview

### ISSUE THREAD

**Issue by rowrowrowrow** [pqina/filepond-plugin-file-poster#7]
Hi,

I'd like to use both FilePoster and ImagePreview at the same time to view local images and newly added images. Using both, posters are loaded properly but the preview size is incorrect and previews for new images are correct. Is there anyway to resolve this? A quick solution for me would be to pass image dimensions in metadata that will be used instead of any calculated dimensions. Happy to help.

**Comment by rikschennink** [comment]
@rowrowrowrow Currently you can't use them both. Maybe a filter property for both plugins would be useful? So you can filter file items and determine which ones you want to use the plugin for?

**Comment by rowrowrowrow** [comment]
That sounds like a good direction, easier than sending the dimensions yourself. How would they be filtered? By some metadata property?

**Comment by rikschennink** [comment]
Yea, or by other properties the developer can use. Each plugin would call a filter hook, then you can determine to block or allow a file.

**Comment by rowrowrowrow** [comment]
That works even better. Thanks for the input and attention!!

**Comment by rikschennink** [comment]
Okay, will probably add this somewhere later this week.

**Comment by rowrowrowrow** [comment]
Thanks! Can't wait!!!

**Comment by rikschennink** [comment]
@rowrowrowrow Both plugins have been updated. Image preview now at `4.5.0`, file poster at `2.2.0`. Image preview has a `imagePreviewFilterItem` property and file poster now has a `filePosterFilterItem` property. Both can be set to a function that receives the file item and should return a boolean.

```js
FilePond.create({
    imagePreviewFilterItem: item => {
        // determine if should show preview
        return true;
    },
    filePosterFilterItem: item => {
        // determine if should show poster
        return false;
    }
})
```

**Comment by rowrowrowrow** [comment]
Hey, just tried it out. Works amazingly well thank you so much for taking the time to create this feature. I really appreciate it!

**Comment by rikschennink** [comment]
@rowrowrowrow Fantastic, glad to hear that :)
